# CREATE statement for itemabstract
CREATE TABLE  `ItemIds` (
  `IID_ID` int(4) NOT NULL auto_increment,
  `IID_NAME` varchar(255) NOT NULL,
  PRIMARY KEY  USING BTREE (`IID_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

# CREATE statement for itemparameterabstract
CREATE TABLE  `ParamIds` (
  `PID_PARAM_ID` int(4) NOT NULL auto_increment,
  `PID_ITEM_ID` int(4) NOT NULL,
  `PID_PARAM_NAME` varchar(50) NOT NULL,
  PRIMARY KEY  USING BTREE (`PID_PARAM_ID`),
  UNIQUE KEY `UNIQUE` (`PID_ITEM_ID`,`PID_PARAM_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

# CREATE statement for item
CREATE TABLE `Item` (
  `I_ID` bigint(8) unsigned NOT NULL AUTO_INCREMENT,
  `I_TYPE_ID` int(4) NOT NULL,
  `I_KEY` varchar(250) DEFAULT NULL,
  `I_T_KEY` varchar(250) DEFAULT NULL,
  `I_PARENT_ID` bigint(8) NOT NULL DEFAULT '0',
  `I_PRED_ID_PATH` varchar(255) DEFAULT NULL,
  `I_REF_ID` bigint(8) unsigned NOT NULL,
  `I_WEIGHT` int(4) unsigned NOT NULL DEFAULT '0',
  `I_OWNER_GROUP_ID` bigint(8) unsigned NOT NULL,
  `I_OWNER_USER_ID` bigint(8) unsigned NOT NULL,
  `I_PARAMS` longtext,
  `I_UPDATED` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`I_ID`),
  KEY `SEARCH` (`I_REF_ID`, `I_WEIGHT`),
  KEY `WEIGHT` (`I_PARENT_ID`,`I_WEIGHT`),
  KEY `SIMPLE_SELECT` (`I_TYPE_ID`,`I_PARENT_ID`,`I_WEIGHT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

# CREATE statement for UniqueKey
CREATE TABLE `UniqueKey` (
  `UK_ITEM_ID` bigint(8) unsigned NOT NULL,
  `UK_KEY` varchar(250) NOT NULL,
  PRIMARY KEY (`UK_ITEM_ID`),
  UNIQUE KEY `UK_KEY_UNIQUE` (`UK_KEY`),
  CONSTRAINT `FK_ITEM` FOREIGN KEY (`UK_ITEM_ID`) REFERENCES `Item` (`I_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

# CREATE statement for ItemParent
CREATE TABLE `ItemParent` (
  `IP_ITEM_ID` bigint(8) unsigned NOT NULL,
  `IP_PARENT_ID` bigint(8) unsigned NOT NULL,
  `IP_LEVEL` int(4) unsigned NOT NULL,
  `IP_REF_ID` bigint(8) unsigned NOT NULL,
  `IP_TYPE` int(4) NOT NULL,
  PRIMARY KEY (`IP_PARENT_ID`,`IP_TYPE`,`IP_ITEM_ID`,`IP_REF_ID`,`IP_LEVEL`) USING BTREE,
  KEY `ITEM` (`IP_REF_ID`),
  CONSTRAINT `ITEM` FOREIGN KEY (`IP_REF_ID`) REFERENCES `Item` (`I_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

# CREATE statement for IntIndex
CREATE TABLE `IntIndex` (
  `II_REF_ID` bigint(20) unsigned NOT NULL,
  `II_PARAM` int(4) NOT NULL,
  `II_TYPE` int(4) NOT NULL,
  `II_VAL` bigint(20) NOT NULL,
  `II_PARENT` bigint(20) unsigned NOT NULL,
  PRIMARY KEY (`II_PARAM`,`II_VAL`,`II_PARENT`,`II_TYPE`,`II_REF_ID`),
  KEY `DEL_ITEM` (`II_REF_ID`),
  CONSTRAINT `II_PARAM` FOREIGN KEY (`II_PARAM`) REFERENCES `ParamIds` (`PID_PARAM_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `II_ITEM` FOREIGN KEY (`II_REF_ID`) REFERENCES `Item` (`I_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

# CREATE statement for DoubleIndex
CREATE TABLE `DoubleIndex` (
  `II_REF_ID` bigint(20) unsigned NOT NULL,
  `II_PARAM` int(4) NOT NULL,
  `II_TYPE` int(4) NOT NULL,
  `II_VAL` double NOT NULL,
  `II_PARENT` bigint(20) unsigned NOT NULL,
  PRIMARY KEY (`II_PARAM`,`II_VAL`,`II_PARENT`,`II_TYPE`,`II_REF_ID`),
  KEY `DI_ITEM` (`II_REF_ID`),
  CONSTRAINT `DI_PARAM` FOREIGN KEY (`II_PARAM`) REFERENCES `ParamIds` (`PID_PARAM_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `DI_ITEM` FOREIGN KEY (`II_REF_ID`) REFERENCES `Item` (`I_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

# CREATE statement for StringIndex
CREATE TABLE `StringIndex` (
  `II_REF_ID` bigint(20) unsigned NOT NULL,
  `II_PARAM` int(4) NOT NULL,
  `II_TYPE` int(4) NOT NULL,
  `II_VAL` varchar(255) NOT NULL DEFAULT '',
  `II_PARENT` bigint(20) unsigned NOT NULL,
  PRIMARY KEY (`II_PARAM`,`II_VAL`,`II_PARENT`,`II_TYPE`,`II_REF_ID`),
  KEY `ITEM` (`II_REF_ID`),
  CONSTRAINT `SI_ITEM` FOREIGN KEY (`II_REF_ID`) REFERENCES `Item` (`I_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `SI_PARAM` FOREIGN KEY (`II_PARAM`) REFERENCES `ParamIds` (`PID_PARAM_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

# CREATE statement for AssocIndex
CREATE TABLE `AssocIndex` (
  `II_REF_ID` bigint(20) unsigned NOT NULL,
  `II_PARAM` int(4) NOT NULL,
  `II_TYPE` int(4) NOT NULL,
  `II_VAL` bigint(20) unsigned NOT NULL,
  `II_PARENT` bigint(20) unsigned NOT NULL,
  PRIMARY KEY (`II_PARAM`,`II_VAL`,`II_PARENT`,`II_TYPE`,`II_REF_ID`),
  KEY `ITEM` (`II_REF_ID`),
  KEY `ASSOC` (`II_VAL`),
  CONSTRAINT `AI_ASSOC` FOREIGN KEY (`II_VAL`) REFERENCES `Item` (`I_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `AI_ITEM` FOREIGN KEY (`II_REF_ID`) REFERENCES `Item` (`I_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `AI_PARAM` FOREIGN KEY (`II_PARAM`) REFERENCES `ParamIds` (`PID_PARAM_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

# CREATE statement for usergroup
CREATE TABLE `UserGroup` (
  `UG_ID` int(4) unsigned NOT NULL auto_increment,
  `UG_NAME` varchar(50) NOT NULL,
  PRIMARY KEY  (`UG_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

# CREATE statement for users
CREATE TABLE `Users` (
  `U_GROUP` varchar(50) NOT NULL,
  `U_LOGIN` varchar(50) NOT NULL,
  `U_PASSWORD` varchar(50) default NULL,
  `U_DESCRIPTION` text,
  `U_ID` bigint(8) NOT NULL auto_increment,
  PRIMARY KEY  (`U_ID`),
  UNIQUE KEY `USERNAME` (`U_LOGIN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;