# Удаление старых родственных связей (тестовая select-форма)
SELECT ItemParent.* FROM ItemParent
WHERE IP_PARENT_ID IN (SELECT IP_PARENT_ID FROM ItemParent WHERE IP_REF_ID = 902)
AND IP_REF_ID IN (SELECT IP_REF_ID FROM ItemParent wHERE IP_PARENT_ID = 902 UNION SELECT 902)
# Вариант для апдейта MySQL
SELECT IP.* FROM
(SELECT IP_PARENT_ID FROM ItemParent WHERE IP_REF_ID = 2020) AS P,
(SELECT IP_REF_ID FROM ItemParent WHERE IP_PARENT_ID = 2020 UNION SELECT 2020) AS R,
ItemParent AS IP
WHERE
IP.IP_PARENT_ID = P.IP_PARENT_ID AND IP.IP_REF_ID = R.IP_REF_ID


# Создание новых родственных связей (тестовая select-форма)
SELECT T3.IP_PARENT_ID, T1.IP_ITEM_ID, T1.IP_REF_ID, T1.IP_LEVEL + T3.IP_LEVEL + 1 FROM
(SELECT IP_PARENT_ID, IP_LEVEL FROM ItemParent WHERE IP_ITEM_ID = 912 UNION SELECT 912, 0) AS T3,
(SELECT IP_ITEM_ID, IP_REF_ID, IP_LEVEL FROM ItemParent WHERE IP_PARENT_ID = 902 UNION SELECT 902, 902, 0) AS T1
ORDER BY T3.IP_PARENT_ID


# Изменение путей к айтемам-потомкам перемещаемого (тестовая select-форма)
SELECT I_ID, I_KEY, I_TYPE_NAME, REPLACE(I_PRED_ID_PATH, '2/12/892/', '2/12/872/4444/')
FROM ItemParent, Item WHERE IP_PARENT_ID = 902 AND IP_ITEM_ID = I_ID